name: 'BetterShulkerBoxes'
version: 4.1.1
main: net.frostyservices.frostyboxes.Main
author: 'FroostySnoowman, someone0171'
api-version: '1.13'
commands:
  fb:
    description: 'Main FrostyBoxes command'

permissions:
  fb.*:
    description: Grants all BetterShulkerBoxes permissions